(cl:defpackage beginner_tutorials-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "MULTIPLY"
   "<MULTIPLY-REQUEST>"
   "MULTIPLY-REQUEST"
   "<MULTIPLY-RESPONSE>"
   "MULTIPLY-RESPONSE"
  ))

