// Generated by gencpp from file beginner_tutorials/multiply.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_MULTIPLY_H
#define BEGINNER_TUTORIALS_MESSAGE_MULTIPLY_H

#include <ros/service_traits.h>


#include <beginner_tutorials/multiplyRequest.h>
#include <beginner_tutorials/multiplyResponse.h>


namespace beginner_tutorials
{

struct multiply
{

typedef multiplyRequest Request;
typedef multiplyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct multiply
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::multiply > {
  static const char* value()
  {
    return "51d0ada50d2055f1c9c8992c5c64d6e1";
  }

  static const char* value(const ::beginner_tutorials::multiply&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::multiply > {
  static const char* value()
  {
    return "beginner_tutorials/multiply";
  }

  static const char* value(const ::beginner_tutorials::multiply&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::multiplyRequest> should match 
// service_traits::MD5Sum< ::beginner_tutorials::multiply > 
template<>
struct MD5Sum< ::beginner_tutorials::multiplyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::multiply >::value();
  }
  static const char* value(const ::beginner_tutorials::multiplyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::multiplyRequest> should match 
// service_traits::DataType< ::beginner_tutorials::multiply > 
template<>
struct DataType< ::beginner_tutorials::multiplyRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::multiply >::value();
  }
  static const char* value(const ::beginner_tutorials::multiplyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::multiplyResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorials::multiply > 
template<>
struct MD5Sum< ::beginner_tutorials::multiplyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::multiply >::value();
  }
  static const char* value(const ::beginner_tutorials::multiplyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::multiplyResponse> should match 
// service_traits::DataType< ::beginner_tutorials::multiply > 
template<>
struct DataType< ::beginner_tutorials::multiplyResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::multiply >::value();
  }
  static const char* value(const ::beginner_tutorials::multiplyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_MULTIPLY_H
